server:
  url-base: UrlBase
  port: 9180
  forward-headers-strategy: native
  ssl: #Configuracion HTTPS
    enabled: true
    key-store: ${server.ssl.key-store}
    key-store-password: ${server.ssl.key-store-password}
    key-store-type: ${server.ssl.key-store-type}
    key-alias: autofirmadov3
app:
  version: 8.1
  security:
    jwt:
      secret: ${jwt.secret}
      expiration: ${jwt.expiration}
spring:
  datasource: #Datasource Oracle
    #    jndi-name: weblogic/datasources/GeforexDS
    url: jdbc:oracle:thin:@${ds.oracle.server.host}:${ds.oracle.server.port}/${ds.oracle.server.service-name}
    username: ${ds.oracle.db.owner-name}
    password: ${ds.oracle.db.password}
    driver-class-name: ${ds.oracle.driver}
    hikari:
      maximum-pool-size: 3
  jpa:
    show-sql: true
    hibernate:
      dialect: ${ds.oracle.dialect}
      format: true
