server:
  url-base: UrlBase
  port: 9110
  forward-headers-strategy: native
  ssl: #Configuracion HTTPS
    enabled: true
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
app:
  version: 8.1
  security:
    jwt:
      secret: ${app.security.jwt.secret}
      expiration: 86400
spring:
  datasource: #Datasource Oracle
    #    jndi-name: weblogic/datasources/GeforexDS
    hikari:
      maximum-pool-size: 3
    url: jdbc:oracle:thin:@${ds.oracle.server.host}:${ds.oracle.server.port}/${ds.oracle.server.service-name}
    username: ${ds.oracle.db.owner-name}
    password: ${ds.oracle.db.password}
    driver-class-name: ${ds.oracle.driver}
  jpa:
    show-sql: true
    hibernate:
      dialect: ${ds.oracle.dialect}
      format: true
