server:
  port: 9110
  forward-headers-strategy: native
  ssl: #Configuracion HTTPS
    enabled: true
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
app:
  version: 8.1
  security:
    jwt:
      secret: askljdhfgenerarclaveconalgunaherramientacomokeypassasdasdggf
      expiration: 86400
spring:
  datasource: #Datasource Oracle
    #    jndi-name: weblogic/datasources/GeforexDS
    hikari:
      maximum-pool-size: 3
    url: jdbc:oracle:thin:@${app.oracle.server.host}:${app.oracle.server.port}/${app.oracle.service.name}
    username: agr_gesfor_app
    password: gesforD3sC0n
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.Oracle8iDialect
      format: true
