server:
  port: ${app.crud-user-server-port}
  forward-headers-strategy: native
  ssl:
    enabled: false
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
spring:
  datasource:
    url: jdbc:oracle:thin:@${app.oracle-server-host}:${app.oracle-server-port}/${app.oracle-service-name}
    username: ${app.oracle-db-owner-name}
    password: ${app.oracle-db-password}
    driver-class-name: ${app.oracle-driver}
  jpa:
    show-sql: true
    hibernate:
      dialect: ${app.oracle-dialect}
      format: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
app:
  security:
    jwt:
      secret: askljdhfgenerarclaveconalgunaherramientacomokeypassasdasdggf
      expiration: 86400





