#GATEWAY
server:
  port: ${app.gateway-server-port}
  forward-headers-strategy: native
  ssl:
    enabled: false
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: security/*
          uri: http://${app.host}:${app.security-server-port}/
          predicates:
            - Path=/auth/**

        - id: crud-user.usuarios
          uri: http://${app.host}:${app.crud-user-server-port}/usuarios/
          predicates:
            - Path=/usuarios/**

        - id: crud-user.permisos
          uri: http://${app.host}:${app.crud-user-server-port}/permisos/
          predicates:
            - Path=/permisos/**

        - id: crud-user.acercade
          uri: http://${app.host}:${app.crud-user-server-port}/acercade/
          predicates:
            - Path=/crud-user-/acercade/**

        - id: plantilla.acercade # nuevo nombre del route (el que quieras)
          uri: http://localhost:9030/ # url a la que va a redirigir el las peticiones (**:puerto_del_servicio)
          predicates:
            - Path=/acercadeplantilla/** # que url va a redirigir al servicio

        - id: tablas # ESTA TIENE QUE SER LA ULTIMA!!!!
          uri: http://localhost:9020/
          predicates:
            - Path=/**
      # routes:
        # - id: plantilla
        #   uri: https://localhost:${app.plantilla-server-port}/
        #   predicates:
        #     - Path=/acercadeplantilla/**
        # - id: auth
        #   uri: http://${app.host}:${app.security-server-port}
        #   predicates:
            - Path=/auth/**
        # - id: producto
        #   uri: https://localhost:443/producto
        #   predicates:
        #     - Path=/producto/**
#        - id: security
#          uri: https://${app.security-server-host}:${app.security-server-port}
#          predicates:
#            - Path=/security/**
# filters:
#   - RewritePath=/localhost/(?<segment>.*), /$\{segment}
#          metadata:
#            - key: X-Forwarded-Proto
#              value: https
#
