server:
  port: ${app.gateway-server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5

spring:
  cloud:
    gateway:
      default-filters[0]: TokenRelay #Deja pasar el token
      routes:
#        - id: security-jwt
#          uri: lb//security-jwt
#          predicates:
#            -Path=/login
        #micoservicio customers http://localhost:8080/customers/hello
        - id: customers-service
          uri: lb://customers-service #lowbalancer
          predicates:
            - Path=/customers/** #lo que llege por la url /customers/ se redirige al customer-service

        - id: users-crud
          uri: lb://users-crud #lowbalancer
          predicates:
            - Path=/users/** #lo que llege a esta url se redirige