server:
  port: ${app.gateway-server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://${app.customer-host}:${app.customer-port}/
          predicates:
            - Path=/customers/** #lo que llege por la url /customers/ se redirige al customer-service
        - id: security
          uri: http://${app.security-server-host}:${app.security-server-port}/
          predicates:
            - Path=/security/**
        - id: hello
          uri: http://${app.security-server-host}:${app.security-server-port}/
          predicates:
            - Path=/hello/**
          filters:
            - TokenRelay=
