server:
  port: ${app.gateway-server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      routes:
      - id: custopmers
        uri: http://localhost:8090/
        predicates:
        - Path=/customers/**
