server:
  port: ${app.gateway-server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5

spring:
  cloud:
    gateway:
      routes:
#        - id: security-jwt
#          uri: lb//security-jwt
#          predicates:
#            -Path=/login
        #micoservicio customers http://localhost:8080/customers/hello
        - id: customers-service
          uri: lb://customers-service #lowbalancer
          predicates:
            - Path=/customers-service/**
