app.message: Hola mundo desde GATEWAY
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      routes:
#        - id: security-jwt
#          uri: lb//security-jwt
#          predicates:
#            -Path=/login
        #micoservicio customers http://localhost:8080/customers/hello
        - id: customers-service
          uri: lb://customers-service #lowbalancer
          predicates:
            - Path=/customers-service/**

        - id: security
          uri: lb://security #lowbalancer
          predicates:
            - Path=/security/**
        #OTROS microservicios