server:
  port: ${app.gateway-server-port}
  forward-headers-strategy: native
  ssl:
    enabled: true
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: customers
          uri: http://${app.customer-host}:${app.customer-port}/
          predicates:
            - Path=/customers/**
        - id: security
          uri: https://${app.security-server-host}:${app.security-server-port}
          predicates:
            - Path=/security/**
          # filters:
          #   - RewritePath=/localhost/(?<segment>.*), /$\{segment}
          metadata:
            - key: X-Forwarded-Proto
              value: https