server:
  port: ${app.gateway-server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      routes:
        - id: customers-service
          uri: lb://customers-service #lowbalancer
          predicates:
            - Path=/customers-service/** #lo que llege por la url /customers/ se redirige al customer-service
        - id: security
          uri: lb://security #lowbalancer
          predicates:
            - Path=/security/** #lo que llege por la url /customers/ se redirige al customer-service
