server:
  port: ${app.gateway-server-port}
  forward-headers-strategy: native
  ssl:
    enabled: true
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - UPDATE
              - DELETE
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: product-auth
          uri: https://localhost:443/auth
          predicates:
            - Path=/auth/**
        - id: product
          uri: https://localhost:443/producto
          predicates:
            - Path=/producto/**
        - id: security
          uri: https://${app.security-server-host}:${app.security-server-port}
          predicates:
            - Path=/security/**
          # filters:
          #   - RewritePath=/localhost/(?<segment>.*), /$\{segment}
          metadata:
            - key: X-Forwarded-Proto
              value: https