# server:
#   port: ${app.gateway-server-port}
server:
  port: 443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: myCertLocal

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: https://${app.customer-host}:${app.customer-port}/
          predicates:
            - Path=/customers/**
        - id: security
          uri: https://${app.security-server-host}:${app.security-server-port}
          predicates:
            - Path=/security/**
