#PLANTILLA
server:
  port: 8081
  # forward-headers-strategy: native
  # ssl:
  #   enabled: true
  #   key-store: classpath:AutoFirmV3Store.p12
  #   key-store-password: geforex
  #   key-store-type: PKCS12
  #   key-alias: autofirmadov3
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
#     initialInstanceInfoReplicationIntervalSeconds: 5
#     registryFetchIntervalSeconds: 5
#   instance:
#     leaseRenewalIntervalInSeconds: 5
#     leaseExpirationInSeconds: 5
spring:
  datasource:
    url: jdbc:oracle:thin:@${app.oracle-server-host}:${app.oracle-server-port}/${app.oracle-service-name}
    username: ${app.oracle-db-owner-name}
    password: ${app.oracle-db-password}
    driver-class-name: ${app.oracle-driver}
  jpa:
    show-sql: true
    hibernate:
      dialect: ${app.oracle-dialect}
      format: true
app:
  security:
    jwt:
      secret: askljdhfgenerarclaveconalgunaherramientacomokeypassasdasdggf
      expiration: 86400
