server:
  port: ${app.user_crud-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
#    url: jdbc:oracle://${app.oracle-server}:${app.oracle-port}/${app.oracle-name}
spring:
  datasource:
    url: jdbc:oracle:thin:@${app.oracle-server}:${app.oracle-port}/${app.oracle-service-name}
#    url: jdbc:oracle:thin:${app.oracle-server}:${app.oracle-port}:${app.oracle-name}
    username: agr_gesfor
    password: gesfordesowner
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle8iDialect
        format: true

