server:
  port: ${app.oracle-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
spring:
  datasource:
    url: jdbc:oracle:thin:@${app.oracle-server}:${app.oracle-port}/${app.oracle-service-name}
    username: ${app.oracle-owner-name}
    password: ${app.oracle-password}
    driver-class-name: ${oracle.jdbc.OracleDriver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ${app.oracle-dialect}
        format: true

